# -*- coding: utf-8 -*-
"""26FebLab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XoIEWGwAR3yKiVNCr08DRtjz-65lzQA8
"""

#1
b=list(map(int,input("Enter sequence: ").split()))
for i in b:
  if(i==i+1):
    print("same")
  else:
    print("different")

#2
import math
A=int(input("Please enter the lenght: "))
B=int(input("Please enter the width: "))
C=math.sqrt(A**2+B**2)
print("The Hypotenuse is: ",C)

#3
name=input("Please enter your first and last name: ")
def Reverse():
  result=""
  for letter in range(len(name)-1,-1,-1):
    result=result+name[letter]
  return result

print(Reverse())

#4
n=int(input("Please enter an integer n: "))
final=n+n*n+n*n*n
print("n+nn+nnn is equal to: ",final)

#5
print("Please enter three integers: ")
d=int(input())
e=int(input())
f=int(input())
if(d>e>f or f>e>d):
  print("The median is: ",e)
elif(e>d>f or f>d>e):
  print("The median is: ",d)
else:
  print("The median is: ",f)
