# -*- coding: utf-8 -*-
"""03/04 lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_2uzMv3dQyscTTYOyQpj6WAofT2vxTu
"""

#1
a=int(input("Please enter first number: "))
b=int(input("Please enter second number: "))
c=int(input("Please enter third number: "))
def maximum():
  print(max(a,b,c))
maximum()

#2
import math
multiply=[8,2,3,-1,7]
for i in range(len(multiply)):

#3
def PrimeChecker():
  import random
  a=int(input("Please enter a number: "))
  if(a<0):
    return "Negative number can't be prime number."
  elif(a>5 and a/a==1 and a/1==a and a%2!=0 and a%3!=0 and a%5!=0):
    return True
  elif(a==2 or a==3 or a==5):
    return True
  return False

PrimeChecker()

#4 Perfect numbers
def divisor(n):
  i=1
  while(i<=n):
    if(n%i==0):
      return i
    i+=1

def PerfectChecker():
  b=int(input())
  for i in divisor(b):
    while(i<b):
      sum=
    
PerfectChecker()