# -*- coding: utf-8 -*-
"""2MarchLab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1068xamRt4k53ACGP8gBTpCPpyIWhoe2B
"""

#1 Dividible by 7, but not a multiple of 5
listOfNumbers=[]
for i in range(2000,3201):
  if(i%7==0 and i%5!=0):
    listOfNumbers.append(i)
print(listOfNumbers)

#2 Factorial

n=int(input())
print(math.factorial(n))

#2 Factorial (another way)
num=int(input())
factorial=1
if(num<0):
  print("No Factorial")
elif(num==0):
  print("Factorial is 1")
else:
  for i in range(1,num + 1):
    factorial = factorial*i
  print("The factorial of",num,"is",factorial)

#3
N=int(input())
NewDict={}
for k in range(1,N+1):
  NewDict[k]=k**2
print(NewDict)
