# -*- coding: utf-8 -*-
"""04/08 lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/109l0ktJxDt8gEFUwdlc5I5KoQ3qU8ofv
"""

# Lab Assignment 3
#1 find 3
def counting(n):
  c=0
  for i in range(0,n+1):
    a=list(map(int,str(i)))
    if 3 in a:
      c+=1
  return c

counting(100)
#I couldn't do for 33,133... cases

#2 Sum of prime numbers
def primeCheck(n):
  import math
  if n <= 1: 
    return False      
  elif n == 2: 
    return n          
  elif n%2 == 0: 
      return False        
  for i in range(3, int(math.sqrt(n))+1, 2): 
    if n%i == 0: 
      return False
  return n

def primeList(n):
  lst=[]
  for i in range(1,n+1):
    if i==primeCheck(i):
      lst.append(i)
  return lst

def answer(n):
  for k in primeList(n):
    if (n-k) in primeList(n):
      print(n,"=",k,"+",n-k)
answer(30)

matrix=[[1,2,3],[4,5,6],[7,8,9]]
def row(matrix):
  for i in range(len(matrix)):
    print("Sum of row",i+1,"is",sum(matrix[i]))

def column(matrix):
  col1=matrix[0][0]+matrix[0][1]+matrix[0][2]
  col2=matrix[1][0]+matrix[1][1]+matrix[1][2]
  col3=matrix[2][0]+matrix[2][1]+matrix[2][2]
  print("Sum of column 1 is",col1,"\n"+"Sum of column 2 is",col2,"\n"+"Sum of column 3 is",col3,"\n")

def greatest(matrix):
  great=[max(matrix[0]),max(matrix[1]),max(matrix[2])]
  print("The greatest sum is ",sum(great))
row(matrix)
print("\n")
column(matrix)
greatest(matrix)