# -*- coding: utf-8 -*-
"""04/01 lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e5T3Ls5c7Nr2O_-sKGTT99Exkh87T_Lg
"""

#1 number of digits 
n=876678009
count=0
for i in str(n):
  count+=1
print(count)

#2 Friendly pair
def SumOfDivisors(n): 
  div=[]
  i = 1
  while i <= n : 
    if (n % i==0): 
      div.append(i)

    i = i + 1
  return sum(div)

def friendly(a,b):
  if (SumOfDivisors(a)/a==SumOfDivisors(b)/b):
    return "Friendly Pair"
  return "Not Friendly Pair"

print(friendly(6,28))

#3 Pascal triangle 
def pascal(n):
  for l in range(1,n+1):
    count=1
    for i in range(1,l+1):
      print(count,end=" ")
      count=int(count*(l-i)/i)
    print ("")
pascal(6)

#4 Handshakes
def shakes(a):
  return int((a*(a-1))/2)

shakes(15)

#5 Armstrong number
def SumOfDigits(num):
  sumlist=[]
  n=len(str(num))
  for i in str(num):
    sumlist.append(int(i)**n)
  return sum(sumlist)

def ArmsCheck(num):
  if SumOfDigits(num)==num:
    return True 
  return False

ArmsCheck(54748)