# -*- coding: utf-8 -*-
"""24FebLab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lbBeyb2KRRpoOWL-m08Qvi2KC4oZjncv
"""

#1
print("Please enter an integer: ")
a=int(input())
if(a%2==0):
  print("Even")
else:
  print("Odd")
if(a%4==0):
  print("The number is divisible by 4" )

#1.c
print("Please enter two numbers: ")
num=int(input())
num2=int(input())
if(num%num2==0):
  print("Congrats! They are divisible")
else:
  print("Try something else")

#2
print("Please enter a number: ")
b=int(input())
if(0<b<10):
  print("Please enter another number: ")
  c=int(input())
elif(20<c<100 or 20<b<100):
  print("Your number is between 20 and 100")
else:
  print("Enter a string: ")
  d=str(input())

#3
print("Please enter a letter(character): ")
e=str(input())
vowels=["a","e","o","i","u"]
if(e in vowels):
  print("You won!")
else: 
  print("You lost!")

#4
print("Please enter two numbers: ")
x=int(input())
y=int(input())
formula=(x+y)*(x+y)
print("(",x,"+",y,")","*2)=",formula)

print("Please enter two integers x,y: ")
u=int(input())
q=int(input())
print("Now I'm going to swap them: x=",q,"y=",u)